import fs from 'node:fs';import path from 'node:path';import {fileURLToPath}from'node:url';
import {buildCharacter}from'./model.mjs';import {readReference,retarget}from'./motions.mjs';import * as T from '../dist/vendor/three.module.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),dest=path.resolve(here,'../dist/models-v5');fs.mkdirSync(dest,{recursive:true});
const cache=path.join(here,'reference-motion.json');
if(!fs.existsSync(cache)){const input=process.argv[2];if(!input)throw Error('Pass the official KayKit Knight.glb reference path on first build');fs.writeFileSync(cache,JSON.stringify(readReference(input)));}
const reference=JSON.parse(fs.readFileSync(cache));
for(const type of ['vampire','wolf','human']){
 const model=buildCharacter(type),clips=retarget(model,reference),parts=[];let bytes=0;
 const g={asset:{version:'2.0',generator:'Nocturne character atelier V5'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[],skins:[],materials:[],textures:[],images:[],samplers:[{magFilter:9729,minFilter:9987,wrapS:33071,wrapT:33071}],accessors:[],bufferViews:[],buffers:[{byteLength:0}],animations:[],extras:{edition:5,height:3,headUnit:1,type,weaponTip:model.weaponTip,clips:Object.fromEntries(clips.map(c=>[c.name,{duration:c.duration,contact:c.contact,source:c.source}])),motionCredit:'Kay Lousberg / KayKit Adventures, CC0; retargeted to original Nocturne models'}};
 function view(b){const pad=(4-bytes%4)%4;if(pad){parts.push(Buffer.alloc(pad));bytes+=pad;}const id=g.bufferViews.length;g.bufferViews.push({buffer:0,byteOffset:bytes,byteLength:b.byteLength});parts.push(b);bytes+=b.byteLength;return id;}
 function acc(a,type,component=5126,bounds=false){const C=component===5126?Float32Array:component===5123?Uint16Array:Uint32Array,n={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16}[type],data=new C(a),entry={bufferView:view(Buffer.from(data.buffer)),componentType:component,count:a.length/n,type};if(bounds){entry.min=Array(n).fill(Infinity);entry.max=Array(n).fill(-Infinity);a.forEach((v,i)=>{entry.min[i%n]=Math.min(entry.min[i%n],v);entry.max[i%n]=Math.max(entry.max[i%n],v);});}g.accessors.push(entry);return g.accessors.length-1;}
 const textures=new Map();function tex(name){const file=name.startsWith('face-')?'face-atlas.png':name+'.png';if(textures.has(file))return textures.get(file);const id=g.images.length;g.images.push({bufferView:view(fs.readFileSync(path.resolve(here,'../dist/art-04',file))),mimeType:'image/png'});g.textures.push({sampler:0,source:id});textures.set(file,id);return id;}
 const materialIds={};for(const [name,m]of Object.entries(model.materials)){if(!model.batches.has(name))continue;const color=new T.Color(m.color);const pbr={baseColorFactor:[color.r,color.g,color.b,1],metallicFactor:m.metalness||0,roughnessFactor:m.roughness||.83};if(m.texture&&m.texture!=='damask')pbr.baseColorTexture={index:tex(m.texture)};const mat={name,pbrMetallicRoughness:pbr,doubleSided:!!m.doubleSided};if(m.emissive){const c=new T.Color(m.emissive);mat.emissiveFactor=c.toArray();}if(name==='face')Object.assign(mat,{alphaMode:'MASK',alphaCutoff:.5});materialIds[name]=g.materials.length;g.materials.push(mat);}
 const index=Object.fromEntries(model.bones.map((b,i)=>[b.name,i]));
 for(const b of model.bones){const p=model.bones[index[b.parent]];g.nodes.push({name:b.name.replaceAll('.','_'),translation:b.position.map((v,i)=>v-(p?.position[i]||0)),children:[]});}
 model.bones.forEach((b,i)=>{if(b.parent)g.nodes[index[b.parent]].children.push(i);else g.scenes[0].nodes.push(i);});
 const inv=[];for(const b of model.bones)inv.push(...new T.Matrix4().makeTranslation(...b.position.map(v=>-v)).elements);
 g.skins.push({name:type+'_skeleton',joints:model.bones.map((_,i)=>i),skeleton:0,inverseBindMatrices:acc(inv,'MAT4')});
 const primitives=[];for(const [name,b]of model.batches){if(name==='face'||name==='wolfFace')for(let i=0;i<b.uv.length;i+=2){if(name==='face')b.uv[i]=b.uv[i]*.5+(type==='human'?.5:0);b.uv[i+1]=1-b.uv[i+1];}primitives.push({attributes:{POSITION:acc(b.p,'VEC3',5126,true),NORMAL:acc(b.n,'VEC3'),TEXCOORD_0:acc(b.uv,'VEC2'),JOINTS_0:acc(b.j,'VEC4',5123),WEIGHTS_0:acc(b.w,'VEC4')},indices:acc(b.idx,'SCALAR',b.p.length/3>65535?5125:5123),material:materialIds[name]});}
 g.meshes.push({name:type+'_weighted_mesh',primitives});g.scenes[0].nodes.push(g.nodes.length);g.nodes.push({name:type+'_model',mesh:0,skin:0});
 for(const c of clips){const anim={name:c.name,samplers:[],channels:[]},input=acc(c.times,'SCALAR',5126,true);c.rotations.forEach((r,i)=>{anim.channels.push({sampler:anim.samplers.length,target:{node:i,path:'rotation'}});anim.samplers.push({input,output:acc(r,'VEC4'),interpolation:'LINEAR'});});anim.channels.push({sampler:anim.samplers.length,target:{node:index.hips,path:'translation'}});anim.samplers.push({input,output:acc(c.hips,'VEC3'),interpolation:'LINEAR'});g.animations.push(anim);}
 const pad=(4-bytes%4)%4;if(pad){parts.push(Buffer.alloc(pad));bytes+=pad;}g.buffers[0].byteLength=bytes;
 let json=Buffer.from(JSON.stringify(g));json=Buffer.concat([json,Buffer.alloc((4-json.length%4)%4,32)]);const head=Buffer.alloc(20);head.writeUInt32LE(0x46546c67,0);head.writeUInt32LE(2,4);head.writeUInt32LE(28+json.length+bytes,8);head.writeUInt32LE(json.length,12);head.writeUInt32LE(0x4e4f534a,16);const binhead=Buffer.alloc(8);binhead.writeUInt32LE(bytes);binhead.writeUInt32LE(0x004e4942,4);fs.writeFileSync(path.join(dest,type+'.glb'),Buffer.concat([head,json,binhead,...parts]));
 console.log(type,model.bones.length+' joints',primitives.reduce((n,p)=>n+g.accessors[p.attributes.POSITION].count,0)+' vertices',clips.length+' clips',bytes+' bytes');
}
