import fs from'node:fs';import assert from'node:assert/strict';import*as T from'../dist/vendor/three.module.mjs';import{GLTFLoader}from'../dist/vendor/loaders/GLTFLoader.mjs';import{clone}from'../dist/vendor/utils/SkeletonUtils.mjs';import{animateV5,playAction,setMotion}from'../dist/characters-v5.mjs';import{CombatPerformance}from'../dist/performance-v5.mjs';
globalThis.ProgressEvent=class{constructor(type,props){Object.assign(this,{type},props);}};
let checks=0;const check=(value,label)=>{assert.ok(value,label);checks++;};const loaded={};
for(const type of ['vampire','wolf','human']){
 const b=fs.readFileSync('dist/models-v5/'+type+'.glb'),len=b.readUInt32LE(12),g=JSON.parse(b.subarray(20,20+len));check(b.readUInt32LE(8)===b.length,type+' GLB length');check(g.skins[0].joints.length===28,'28 joints');check(g.animations.length===9,'9 clips');
 // Test real loader, bones and weights without requiring a GPU or PNG decoder.
 g.images=[];g.textures=[];g.materials.forEach(m=>delete m.pbrMetallicRoughness.baseColorTexture);g.buffers[0].uri='data:application/octet-stream;base64,'+b.subarray(28+len).toString('base64');const asset=await new GLTFLoader().parseAsync(JSON.stringify(g),'');loaded[type]=asset;
 let verts=0;asset.scene.traverse(o=>{if(o.isSkinnedMesh){const p=o.geometry.attributes.position,w=o.geometry.attributes.skinWeight;verts+=p.count;for(let i=0;i<p.count;i++){check(Number.isFinite(p.getX(i)+p.getY(i)+p.getZ(i)),'finite vertices');check(Math.abs(w.getX(i)+w.getY(i)+w.getZ(i)+w.getW(i)-1)<.00001,'weights sum to one');}}});
 const root=make(type),d=root.userData;const knee=d.model.getObjectByName('lowerleg_r'),elbow=d.model.getObjectByName('lowerarm_r');let q0=knee.quaternion.clone(),q1=elbow.quaternion.clone();setMotion(root,'walk',0);d.mixer.update(.24);check(q0.angleTo(knee.quaternion)>.10,'knee bends during walk');check(q1.angleTo(elbow.quaternion)>.05,'elbow bends during walk');
 for(const clip of asset.animations){d.mixer.stopAllAction();d.current=null;setMotion(root,clip.name,0);for(let k=0;k<5;k++){d.actions[clip.name].time=clip.duration*k/4;d.mixer.update(0);d.model.updateMatrixWorld(true);d.model.traverse(o=>{if(o.isSkinnedMesh){o.skeleton.update();for(let i=0;i<o.geometry.attributes.position.count;i+=101){const p=new T.Vector3().fromBufferAttribute(o.geometry.attributes.position,i);o.applyBoneTransform(i,p);check(Number.isFinite(p.length())&&p.length()<8,clip.name+' no exploding skin');}}});}}
 d.mixer.stopAllAction();d.current=null;setMotion(root,'idle',0);playAction(root,'attack');for(let i=0;i<120;i++)animateV5(root,1/60,0);check(d.current==='idle'&&!d.locked,'attack returns to idle');playAction(root,'death');for(let i=0;i<150;i++)animateV5(root,1/60,0);check(d.current==='death'&&d.locked,'death holds final pose');
 const other=make(type);check(other.userData.model.getObjectByName('head')!==d.model.getObjectByName('head'),'clones have independent bones');console.log(type,verts+' weighted vertices',asset.animations.map(c=>c.name).join(','));
}
function make(type){const asset=loaded[type],root=new T.Group(),model=clone(asset.scene),mixer=new T.AnimationMixer(model);root.add(model);root.userData={edition:5,type,model,mixer,actions:Object.fromEntries(asset.animations.map(c=>[c.name,mixer.clipAction(c)])),current:null,meta:asset.parser.json.extras.clips};setMotion(root,'idle',0);mixer.update(0);return root;}
const hero=make('vampire'),target=new T.Group(),second=new T.Group();target.position.set(0,0,5);second.position.set(2,0,5);let contacts=0,done=0,impacts=0;const world={actors:{vampire:hero,e0:target,e1:second},impact(){impacts++;}},perf=new CombatPerformance(world);
perf.enqueue('vampire',['e0','e1'],'attack',()=>contacts++,()=>done++);for(let i=0;i<20;i++){perf.update(.01);animateV5(hero,.01,7);}check(contacts===0,'no early damage while approaching');const frozen=hero.position.clone();for(let i=0;i<20;i++)perf.update(0);check(hero.position.equals(frozen)&&contacts===0,'pause freezes position and contact');for(let i=0;i<500;i++){perf.update(.01);animateV5(hero,.01,hero.userData.combatMoving?7:0);}check(contacts===1&&impacts===2,'AoE one motion/contact, two effects');check(done===1&&!perf.busy,'completion exactly once');check(hero.position.length()<.00001,'returns to starting point');
console.log('PASS',checks,'asset, skin, animation and combat presentation checks');
